### ISSUE TITLE
Patient launch not returning patient

### ISSUE THREAD

**Issue by brettmarquard** [cds-hooks/legacy-sandbox#100] opened 2018-01-28 16:40 UTC
I created a new HSPC sandbox to launch CDS Hooks SMART App - worked perfectly!

Then I tried to 'change patients' and when I selected a new patient, my HSPC server returned a 404.

CDS hooks sandbox sent: https://api-v5-dstu2.hspconsortium.org/wo/data/Patient/SMART-1551992 

Patient id is now - 2760 (Lisa Coleman).

Using postman, this query does work: https://api-v5-dstu2.hspconsortium.org/wo/data/Patient?identifier=http://hospital.smarthealthit.org|1551992 

Maybe HSPC team moved all 'SMART-1551992' ids to identifier

**Comment by travistcummings** [comment] 2018-01-31 18:59
The issue is that our starter dataset for HSPC DSTU2 sandbox instances is messed up.  It doesn't contain the user-provided id values for the resources.  We will get a fix our for this today.

**Comment by zplata** [comment] 2018-02-01 16:16
@brettmarquard Can you check again and see if you're still seeing the issue?

**Comment by kpshek** [comment] 2018-05-17 14:35
Closing out graveyard issues on the deprecated legacy Sandbox. If this issue is still desired, please log an issue against our new [sandbox](https://github.com/cds-hooks/sandbox/issues).

**Closed as completed by kpshek** 2018-05-17 14:35 UTC

**Comment by dennispatterson** [comment] 2019-08-27 15:44
Closing for now.  Any changes from Gay can be added later
